name: wm_jaya
description: Aplikasi manajemen toko sederhana dengan sistem CRUD offline.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  provider: ^6.1.2
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  intl: ^0.19.0
  syncfusion_flutter_charts: ^28.2.11
  material_design_icons_flutter: ^7.0.7296
  flutter_form_builder: ^10.0.1
  flutter_launcher_icons: ^0.14.3
  fl_chart: ^0.70.2
  http: ^1.2.1
  pdf: ^3.11.3
  printing: ^5.14.0
  google_sign_in: ^6.2.2
  googleapis: ^14.0.0
  googleapis_auth: ^1.6.0
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  file_picker: ^9.1.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.3
  synchronized: ^3.3.1
  connectivity_plus: ^6.1.3
  logger: ^2.5.0
  local_auth: ^2.3.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  process_run: ^1.2.4

flutter:
  uses-material-design: true

  # PERBAIKAN: Indentasi dan struktur di bagian ini diperbaiki.
  # Pastikan Anda memiliki folder `assets` dan sub-folder `images`
  # atau sesuaikan path-nya dengan struktur folder Anda.
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: MaterialDesignIcons
      fonts:
        - asset: assets/fonts/materialdesignicons-webfont.ttf

# Konfigurasi untuk package flutter_launcher_icons
# Pastikan file icon.png ada di dalam folder `assets/images/` atau `assets/`
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png" 
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"
